### ISSUE TITLE
Improve you readme 

### ISSUE THREAD

**Issue by wimpywarlord** [wadhwaniv1/To-Do-List-App#1]
Check this link out : https://github.com/vinnovateit/Github_readme_template

**Comment by wadhwaniv1** [comment]
Okay following as per instructions!

**Comment by wadhwaniv1** [comment]
Done!!

**Comment by wimpywarlord** [comment]
These were no instructions, these were just humble suggestions from my side. This is not part of the recruitment process.

**Comment by wimpywarlord** [comment]
Good work btw.

**Comment by wadhwaniv1** [comment]
Thanks for the reference!!!
